name: CI

on:
  push:
  pull_request:

jobs:
  install_ansible:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible and tools
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          pip3 install ansible-lint

          
